endpoint: http://localhost:3000/graphql

schema:
  source: local
  path: /home/mlins/Desktop/nestjs_graphql/src/schema.gql

transport:
  type: stdio

introspection:
  introspect:
    enabled: true

operations:
  source: introspect
