import { InputType } from "@nestjs/graphql";

import { IsNotEmpty, IsString, MaxLength } from "class-validator";

import { Trim } from "@/common/transformer/trim.transformer";

@InputType()
export class VerifyEmailInput {
  /** Raw email verification token generated by a previous successful verification request. */
  @Trim()
  @IsString()
  @IsNotEmpty()
  @MaxLength(512)
  token: string;
}
